apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: codefresh
  namespace: codefresh  
spec:
  # Secret names are always required.
  secretName: codefresh
  dnsNames:
  - test.shubhamk.online
  issuerRef:
    name: codefresh-app
    kind: ClusterIssuer
